# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailchat < Formula
  desc "End-to-end encrypted terminal chat over Tailscale"
  homepage "https://github.com/NathanBhanji/tail-chat"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.6.0/tailchat_darwin_amd64.tar.gz"
      sha256 "a883f1c668e750bf2b726eac7edde5d69e3c73d41632fb59a2092d177217e7f8"

      def install
        bin.install "tailchat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.6.0/tailchat_darwin_arm64.tar.gz"
      sha256 "475ab97df52087490fd3e09e882b621234afe0760fbf34c12de66d671d416114"

      def install
        bin.install "tailchat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.6.0/tailchat_linux_amd64.tar.gz"
      sha256 "331a520a770445e0f16dc73d41071b2d6db18352658f8ec94dd397b426063a25"
      def install
        bin.install "tailchat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.6.0/tailchat_linux_arm64.tar.gz"
      sha256 "e324c7b3aa938bdd7af89dbb44c70a053960e6a9a2b745d43ed273a08c0f27b4"
      def install
        bin.install "tailchat"
      end
    end
  end

  test do
    system "#{bin}/tailchat", "--version"
  end
end
