# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailchat < Formula
  desc "End-to-end encrypted terminal chat over Tailscale"
  homepage "https://github.com/NathanBhanji/tail-chat"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.5.1/tailchat_darwin_amd64.tar.gz"
      sha256 "cb70f9e90de421046b084b06409b3d9812cb8b0c6fb90c42eaec794a37ef3752"

      def install
        bin.install "tailchat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.5.1/tailchat_darwin_arm64.tar.gz"
      sha256 "bcd0ab3c7095d26a9152001a2c7ea594e3ac9283ed48c30f8706f49c9f382af8"

      def install
        bin.install "tailchat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.5.1/tailchat_linux_amd64.tar.gz"
      sha256 "7700b8fb2e4b18d5cb1bcd3255571d3e3bee4dd3406e288d53e28ea9cf427e2b"
      def install
        bin.install "tailchat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NathanBhanji/tail-chat/releases/download/v0.5.1/tailchat_linux_arm64.tar.gz"
      sha256 "04ba61c6f390c1114cd4513b45272f6630e15b0e496af25af4907793078e06d2"
      def install
        bin.install "tailchat"
      end
    end
  end

  test do
    system "#{bin}/tailchat", "--version"
  end
end
